package com.tcl.friendserver.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

@Entity
public class FriendCommentSupport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_comment_support.id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    @Id
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_comment_support.support_id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    private Long supportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_comment_support.user_id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_comment_support.status
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_comment_support.support_time
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    private Date supportTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_comment_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public FriendCommentSupport(Long id, Long supportId, Long userId, Boolean status, Date supportTime) {
        this.id = id;
        this.supportId = supportId;
        this.userId = userId;
        this.status = status;
        this.supportTime = supportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_comment_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public FriendCommentSupport() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_comment_support.id
     *
     * @return the value of friend_comment_support.id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_comment_support.id
     *
     * @param id the value for friend_comment_support.id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_comment_support.support_id
     *
     * @return the value of friend_comment_support.support_id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public Long getSupportId() {
        return supportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_comment_support.support_id
     *
     * @param supportId the value for friend_comment_support.support_id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public void setSupportId(Long supportId) {
        this.supportId = supportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_comment_support.user_id
     *
     * @return the value of friend_comment_support.user_id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_comment_support.user_id
     *
     * @param userId the value for friend_comment_support.user_id
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_comment_support.status
     *
     * @return the value of friend_comment_support.status
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_comment_support.status
     *
     * @param status the value for friend_comment_support.status
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_comment_support.support_time
     *
     * @return the value of friend_comment_support.support_time
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public Date getSupportTime() {
        return supportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_comment_support.support_time
     *
     * @param supportTime the value for friend_comment_support.support_time
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    public void setSupportTime(Date supportTime) {
        this.supportTime = supportTime;
    }
}