package com.tcl.friendserver.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.crowd
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private Integer crowd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.constellation
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String constellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.login
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private Integer login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.signature
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pos_province
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String posProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pos_city
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String posCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pos_district
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String posDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.fans
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private Integer fans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.avatar
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.school
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.major
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.enrollment_year
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String enrollmentYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.industry
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    private String industry;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public UserInfo(Integer id, String nickname, Integer crowd, Integer sex, String birthday, String constellation, Integer login, String signature, String posProvince, String posCity, String posDistrict, Integer fans, String avatar, String school, String major, String enrollmentYear, String industry) {
        this.id = id;
        this.nickname = nickname;
        this.crowd = crowd;
        this.sex = sex;
        this.birthday = birthday;
        this.constellation = constellation;
        this.login = login;
        this.signature = signature;
        this.posProvince = posProvince;
        this.posCity = posCity;
        this.posDistrict = posDistrict;
        this.fans = fans;
        this.avatar = avatar;
        this.school = school;
        this.major = major;
        this.enrollmentYear = enrollmentYear;
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public UserInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nickname
     *
     * @return the value of user_info.nickname
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nickname
     *
     * @param nickname the value for user_info.nickname
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.crowd
     *
     * @return the value of user_info.crowd
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public Integer getCrowd() {
        return crowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.crowd
     *
     * @param crowd the value for user_info.crowd
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setCrowd(Integer crowd) {
        this.crowd = crowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.constellation
     *
     * @return the value of user_info.constellation
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.constellation
     *
     * @param constellation the value for user_info.constellation
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation == null ? null : constellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.login
     *
     * @return the value of user_info.login
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public Integer getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.login
     *
     * @param login the value for user_info.login
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setLogin(Integer login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.signature
     *
     * @return the value of user_info.signature
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.signature
     *
     * @param signature the value for user_info.signature
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pos_province
     *
     * @return the value of user_info.pos_province
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getPosProvince() {
        return posProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pos_province
     *
     * @param posProvince the value for user_info.pos_province
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setPosProvince(String posProvince) {
        this.posProvince = posProvince == null ? null : posProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pos_city
     *
     * @return the value of user_info.pos_city
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getPosCity() {
        return posCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pos_city
     *
     * @param posCity the value for user_info.pos_city
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setPosCity(String posCity) {
        this.posCity = posCity == null ? null : posCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pos_district
     *
     * @return the value of user_info.pos_district
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getPosDistrict() {
        return posDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pos_district
     *
     * @param posDistrict the value for user_info.pos_district
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setPosDistrict(String posDistrict) {
        this.posDistrict = posDistrict == null ? null : posDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.fans
     *
     * @return the value of user_info.fans
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public Integer getFans() {
        return fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.fans
     *
     * @param fans the value for user_info.fans
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setFans(Integer fans) {
        this.fans = fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.avatar
     *
     * @return the value of user_info.avatar
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.avatar
     *
     * @param avatar the value for user_info.avatar
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.school
     *
     * @return the value of user_info.school
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.school
     *
     * @param school the value for user_info.school
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.major
     *
     * @return the value of user_info.major
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.major
     *
     * @param major the value for user_info.major
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.enrollment_year
     *
     * @return the value of user_info.enrollment_year
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getEnrollmentYear() {
        return enrollmentYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.enrollment_year
     *
     * @param enrollmentYear the value for user_info.enrollment_year
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setEnrollmentYear(String enrollmentYear) {
        this.enrollmentYear = enrollmentYear == null ? null : enrollmentYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.industry
     *
     * @return the value of user_info.industry
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.industry
     *
     * @param industry the value for user_info.industry
     *
     * @mbggenerated Thu Aug 15 17:08:33 CST 2019
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }


    /**
     * added by quantai.zhu
     * @param uid
     * @param nickname
     */
    public UserInfo(Integer uid,String nickname) {
        this.id = uid;
        this.nickname = nickname;
    }
}