package com.tcl.friendadmin.mapper;

import com.tcl.friendadmin.model.AdminUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AdminUserMapper {
    AdminUser login(@Param("userName")String userName,@Param("password")String password);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    int deleteByPrimaryKey(Integer adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    int insert(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    int insertSelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    AdminUser selectByPrimaryKey(Integer adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    int updateByPrimaryKeySelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    int updateByPrimaryKey(AdminUser record);
}