package com.tcl.friendadmin.mapper;

import com.tcl.friendadmin.model.Blog;

import java.util.List;

public interface BlogMapper {

    List<Blog> findAllBlogs();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    Blog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    int updateByPrimaryKey(Blog record);
}