package com.tcl.friendadmin.model;

public class AdminUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.admin_user_id
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    private Integer adminUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.login_user_name
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    private String loginUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.password
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.nickname
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    private String nickname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public AdminUser(Integer adminUserId, String loginUserName, String password, String nickname) {
        this.adminUserId = adminUserId;
        this.loginUserName = loginUserName;
        this.password = password;
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public AdminUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.admin_user_id
     *
     * @return the value of admin_user.admin_user_id
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public Integer getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.admin_user_id
     *
     * @param adminUserId the value for admin_user.admin_user_id
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public void setAdminUserId(Integer adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.login_user_name
     *
     * @return the value of admin_user.login_user_name
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public String getLoginUserName() {
        return loginUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.login_user_name
     *
     * @param loginUserName the value for admin_user.login_user_name
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public void setLoginUserName(String loginUserName) {
        this.loginUserName = loginUserName == null ? null : loginUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.password
     *
     * @return the value of admin_user.password
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.password
     *
     * @param password the value for admin_user.password
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.nickname
     *
     * @return the value of admin_user.nickname
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.nickname
     *
     * @param nickname the value for admin_user.nickname
     *
     * @mbggenerated Wed Aug 14 17:38:22 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }
}