package com.tcl.friendadmin.model;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.id
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.uid
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.create_time
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.status
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.is_top
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Byte isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.is_comment
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Byte isComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.support_count
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Integer supportCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.weibo_type
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private String weiboType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.crowd_id
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Long crowdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.repost_count
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private Integer repostCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.from_device
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private String fromDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_weibo.content
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Blog(Long id, Long uid, Date createTime, Byte status, Byte isTop, Byte isComment, Integer supportCount, String weiboType, Long crowdId, Integer repostCount, String fromDevice, String content) {
        this.id = id;
        this.uid = uid;
        this.createTime = createTime;
        this.status = status;
        this.isTop = isTop;
        this.isComment = isComment;
        this.supportCount = supportCount;
        this.weiboType = weiboType;
        this.crowdId = crowdId;
        this.repostCount = repostCount;
        this.fromDevice = fromDevice;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Blog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.id
     *
     * @return the value of friend_weibo.id
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.id
     *
     * @param id the value for friend_weibo.id
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.uid
     *
     * @return the value of friend_weibo.uid
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.uid
     *
     * @param uid the value for friend_weibo.uid
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.create_time
     *
     * @return the value of friend_weibo.create_time
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.create_time
     *
     * @param createTime the value for friend_weibo.create_time
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.status
     *
     * @return the value of friend_weibo.status
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.status
     *
     * @param status the value for friend_weibo.status
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.is_top
     *
     * @return the value of friend_weibo.is_top
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Byte getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.is_top
     *
     * @param isTop the value for friend_weibo.is_top
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setIsTop(Byte isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.is_comment
     *
     * @return the value of friend_weibo.is_comment
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Byte getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.is_comment
     *
     * @param isComment the value for friend_weibo.is_comment
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setIsComment(Byte isComment) {
        this.isComment = isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.support_count
     *
     * @return the value of friend_weibo.support_count
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Integer getSupportCount() {
        return supportCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.support_count
     *
     * @param supportCount the value for friend_weibo.support_count
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setSupportCount(Integer supportCount) {
        this.supportCount = supportCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.weibo_type
     *
     * @return the value of friend_weibo.weibo_type
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public String getWeiboType() {
        return weiboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.weibo_type
     *
     * @param weiboType the value for friend_weibo.weibo_type
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setWeiboType(String weiboType) {
        this.weiboType = weiboType == null ? null : weiboType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.crowd_id
     *
     * @return the value of friend_weibo.crowd_id
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Long getCrowdId() {
        return crowdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.crowd_id
     *
     * @param crowdId the value for friend_weibo.crowd_id
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setCrowdId(Long crowdId) {
        this.crowdId = crowdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.repost_count
     *
     * @return the value of friend_weibo.repost_count
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public Integer getRepostCount() {
        return repostCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.repost_count
     *
     * @param repostCount the value for friend_weibo.repost_count
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setRepostCount(Integer repostCount) {
        this.repostCount = repostCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.from_device
     *
     * @return the value of friend_weibo.from_device
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public String getFromDevice() {
        return fromDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.from_device
     *
     * @param fromDevice the value for friend_weibo.from_device
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setFromDevice(String fromDevice) {
        this.fromDevice = fromDevice == null ? null : fromDevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_weibo.content
     *
     * @return the value of friend_weibo.content
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_weibo.content
     *
     * @param content the value for friend_weibo.content
     *
     * @mbggenerated Tue Aug 13 17:34:07 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}