package com.tcl.friendserver.mapper;

import com.tcl.friendserver.model.FriendWeibo;

public interface FriendWeiboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insert(FriendWeibo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insertSelective(FriendWeibo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    FriendWeibo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKeySelective(FriendWeibo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKey(FriendWeibo record);
}