package com.tcl.friendserver.mapper;

import com.tcl.friendserver.model.FriendWeiboSupport;

public interface FriendWeiboSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insert(FriendWeiboSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insertSelective(FriendWeiboSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    FriendWeiboSupport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKeySelective(FriendWeiboSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKey(FriendWeiboSupport record);
}