package com.tcl.friendserver.mapper;

import com.tcl.friendserver.model.FriendWeiboComment;

public interface FriendWeiboCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insert(FriendWeiboComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insertSelective(FriendWeiboComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    FriendWeiboComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKeySelective(FriendWeiboComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKey(FriendWeiboComment record);
}