package com.tcl.friendserver.mapper;

import com.tcl.friendserver.model.FriendWeiboCommentReply;

public interface FriendWeiboCommentReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment_reply
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment_reply
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insert(FriendWeiboCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment_reply
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insertSelective(FriendWeiboCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment_reply
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    FriendWeiboCommentReply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment_reply
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKeySelective(FriendWeiboCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_weibo_comment_reply
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKey(FriendWeiboCommentReply record);
}