package com.tcl.friendserver.mapper;

import com.tcl.friendserver.model.FriendCommentSupport;

public interface FriendCommentSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_comment_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_comment_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insert(FriendCommentSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_comment_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int insertSelective(FriendCommentSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_comment_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    FriendCommentSupport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_comment_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKeySelective(FriendCommentSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_comment_support
     *
     * @mbg.generated Tue Aug 13 17:44:45 CST 2019
     */
    int updateByPrimaryKey(FriendCommentSupport record);
}